---
- hosts: webservers
  tasks:
  - name: Loob allalaadimiseks kausta
    file:
     path=/root/allalaadimised
     owner=root
     group=root
     mode=0755
     state=directory

  - name: Laeb alla mysql repo paketti
    get_url:
      url: http://repo.mysql.com/mysql-apt-config_0.8.6-1_all.deb
      dest: "/root/allalaadimised"
      mode: 0440

  - name: Installib mysql paki
    apt: "deb=/root/allalaadimised/mysql-apt-config_0.8.6-1_all.deb"

  - name: Installib mysql
    apt: name=mysql-server state=present

  - name: Installib python-mysqldb
    apt: name=python-mysqldb state=latest

  - name: Loome kasutaja 'root' ja anname parooliks 'qwerty' koos root oigustega
    mysql_user:
      name: root
      password: qwerty
      priv: '*.*:ALL,GRANT'
      state: present

  - name: Loome root logimiseks faili
    copy:
      dest: /root/.my.cnf
      owner: root
      group: root
      mode: 0600
      content: |
           [client]
           user=root
           password=qwerty
  - name: Restardib mysql teenuse
    service: name=mysql state=restarted
