---
- hosts: webservers
  tasks:

  - name: Loomb andmebaasi wordpressi jaoks
    mysql_db:
      name: wpdatabase
      state: present

  - name: Loomb kasutaja
    mysql_user:
      name: wpuser
      password: qwerty
      priv: 'wpdatabase.*:ALL,GRANT'
      state: present
      check_implicit_admin: yes
  - name: Restardib mysql
    service: name=mysql state=restarted

  - name: Laeb alla wp ja installib selle
    unarchive:
      src: https://wordpress.org/latest.tar.gz
      dest: /var/www/html/
      remote_src: yes

  - name: Vahetab wp kausta omaniku www-data
    file:
      path: /var/www/html/wordpress/
      state: directory
      recurse: yes
      owner: www-data

  - name: Kopeerib config fail
    command: cp /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php

  - name: Vahetab 'DB_PASSWORD' wordpress config failis
    lineinfile: dest=/var/www/html/wordpress/wp-config.php regexp="password_here'" line="define( 'DB_PASSWORD', 'qwerty' );"

  - name: Vahetab 'DB_USER' wordpress config failis
    lineinfile: dest=/var/www/html/wordpress/wp-config.php regexp="username_here" line="define( 'DB_USER', 'wpuser' );"

  - name: Vahetab 'DB_NAME' wordpress config failis
    lineinfile: dest=/var/www/html/wordpress/wp-config.php regexp="database_name_here" line="define( 'DB_NAME', 'wpdatabase' );"
